name: "Git credentials setup"
description: "Set up git credentials"

runs:
  using: "composite"
  steps:
    - name: Set up git credentials
      shell: bash
      run: |
        git config --global user.name 'ezds-bot'
        git config --global user.email 'ezds@ezcorp.com'
