/**
 * EZDS Tailwind CSS preset.
 *
 * Maps all --ezds-* CSS custom properties into Tailwind utility classes.
 * Import in your tailwind.config.js:
 *
 *   const ezdsPreset = require('@ezds/web/tailwind');
 *   module.exports = { presets: [ezdsPreset] };
 */
module.exports = {
  theme: {
    extend: {
      colors: {
        "ezds-bg-page": "var(--ezds-color-background-page)",
        "ezds-bg-primary": "var(--ezds-color-background-primary)",
        "ezds-bg-secondary": "var(--ezds-color-background-secondary)",
        "ezds-bg-tertiary": "var(--ezds-color-background-tertiary)",
        "ezds-bg-quaternary": "var(--ezds-color-background-quaternary)",
        "ezds-bg-disabled": "var(--ezds-color-background-disabled)",
        "ezds-bg-accent": "var(--ezds-color-background-accent-default)",
        "ezds-bg-accent-subtle": "var(--ezds-color-background-accent-subtle)",
        "ezds-bg-danger": "var(--ezds-color-background-danger-default)",
        "ezds-bg-danger-subtle": "var(--ezds-color-background-danger-subtle)",
        "ezds-bg-warning": "var(--ezds-color-background-warning-default)",
        "ezds-bg-warning-subtle": "var(--ezds-color-background-warning-subtle)",
        "ezds-bg-success": "var(--ezds-color-background-success-default)",
        "ezds-bg-success-subtle": "var(--ezds-color-background-success-subtle)",
        "ezds-bg-info": "var(--ezds-color-background-info-default)",
        "ezds-bg-info-subtle": "var(--ezds-color-background-info-subtle)",
        "ezds-bg-ezpoints": "var(--ezds-color-background-ezpoints-default)",
        "ezds-text-default": "var(--ezds-color-text-default)",
        "ezds-text-subtle": "var(--ezds-color-text-subtle)",
        "ezds-text-subtler": "var(--ezds-color-text-subtler)",
        "ezds-text-subtlest": "var(--ezds-color-text-subtlest)",
        "ezds-text-inverted": "var(--ezds-color-text-default-inverted)",
        "ezds-text-disabled": "var(--ezds-color-text-default-disabled)",
        "ezds-text-accent": "var(--ezds-color-text-accent)",
        "ezds-text-danger": "var(--ezds-color-text-danger-default)",
        "ezds-text-warning": "var(--ezds-color-text-warning-default)",
        "ezds-text-success": "var(--ezds-color-text-success-default)",
        "ezds-text-ezpoints": "var(--ezds-color-text-ezpoints-default)",
        "ezds-icon-default": "var(--ezds-color-icon-default)",
        "ezds-icon-subtle": "var(--ezds-color-icon-subtle)",
        "ezds-icon-accent": "var(--ezds-color-icon-accent)",
        "ezds-border-default": "var(--ezds-color-border-default)",
        "ezds-border-strong": "var(--ezds-color-border-strong)",
        "ezds-border-input": "var(--ezds-color-border-input-default)",
        "ezds-border-accent": "var(--ezds-color-border-accent-default)",
        "ezds-link": "var(--ezds-color-link-default)",
      },
      spacing: {
        "ezds-none": "var(--ezds-space-none)",
        "ezds-25": "var(--ezds-space-0025)",
        "ezds-50": "var(--ezds-space-0050)",
        "ezds-100": "var(--ezds-space-0100)",
        "ezds-150": "var(--ezds-space-0150)",
        "ezds-200": "var(--ezds-space-0200)",
        "ezds-250": "var(--ezds-space-0250)",
        "ezds-300": "var(--ezds-space-0300)",
        "ezds-350": "var(--ezds-space-0350)",
        "ezds-400": "var(--ezds-space-0400)",
        "ezds-450": "var(--ezds-space-0450)",
        "ezds-500": "var(--ezds-space-0500)",
        "ezds-600": "var(--ezds-space-0600)",
        "ezds-700": "var(--ezds-space-0700)",
        "ezds-800": "var(--ezds-space-0800)",
        "ezds-1000": "var(--ezds-space-1000)",
        "ezds-1200": "var(--ezds-space-1200)",
        "ezds-1600": "var(--ezds-space-1600)",
        "ezds-2000": "var(--ezds-space-2000)",
      },
      borderRadius: {
        "ezds-none": "var(--ezds-radius-none)",
        "ezds-100": "var(--ezds-radius-0100)",
        "ezds-150": "var(--ezds-radius-0150)",
        "ezds-200": "var(--ezds-radius-0200)",
        "ezds-250": "var(--ezds-radius-0250)",
        "ezds-300": "var(--ezds-radius-0300)",
        "ezds-400": "var(--ezds-radius-0400)",
        "ezds-500": "var(--ezds-radius-0500)",
        "ezds-600": "var(--ezds-radius-0600)",
        "ezds-700": "var(--ezds-radius-0700)",
        "ezds-800": "var(--ezds-radius-0800)",
        "ezds-full": "var(--ezds-radius-full)",
      },
      fontSize: {
        "ezds-body-xxs": "var(--ezds-font-size-body-xxs)",
        "ezds-body-xs": "var(--ezds-font-size-body-xs)",
        "ezds-body-sm": "var(--ezds-font-size-body-sm)",
        "ezds-body-md": "var(--ezds-font-size-body-md)",
        "ezds-body-lg": "var(--ezds-font-size-body-lg)",
        "ezds-body-xl": "var(--ezds-font-size-body-xl)",
        "ezds-title-xs": "var(--ezds-font-size-title-xs)",
        "ezds-title-sm": "var(--ezds-font-size-title-sm)",
        "ezds-title-md": "var(--ezds-font-size-title-md)",
        "ezds-title-lg": "var(--ezds-font-size-title-lg)",
      },
      lineHeight: {
        "ezds-body-xxs": "var(--ezds-line-height-body-xxs)",
        "ezds-body-xs": "var(--ezds-line-height-body-xs)",
        "ezds-body-sm": "var(--ezds-line-height-body-sm)",
        "ezds-body-md": "var(--ezds-line-height-body-md)",
        "ezds-body-lg": "var(--ezds-line-height-body-lg)",
        "ezds-body-xl": "var(--ezds-line-height-body-xl)",
        "ezds-title-xs": "var(--ezds-line-height-title-xs)",
        "ezds-title-sm": "var(--ezds-line-height-title-sm)",
        "ezds-title-md": "var(--ezds-line-height-title-md)",
        "ezds-title-lg": "var(--ezds-line-height-title-lg)",
      },
    },
  },
};
