const AVATAR_SMALL_SIZE = "small";
const AVATAR_MEDIUM_SIZE = "medium";
const AVATAR_LARGE_SIZE = "large";
export const AVATAR_SIZES = {
  SMALL: AVATAR_SMALL_SIZE,
  MEDIUM: AVATAR_MEDIUM_SIZE,
  LARGE: AVATAR_LARGE_SIZE
};
